# Generated by Django 4.0.4 on 2022-05-17 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name_item_options', models.CharField(db_index=True, max_length=50)),
                ('price_item_options', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Product_name_item_options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraItemOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name_extra_item_options', models.CharField(db_index=True, max_length=50)),
                ('price_extra_item_options', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Product_name_extra_item_options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_extra', to='shop.product')),
            ],
        ),
    ]
