# Generated by Django 4.0.4 on 2022-05-17 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_itemoptions_extraitemoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraitemoptions',
            name='Product_name_extra_item_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_extra_options', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='itemoptions',
            name='Product_name_item_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_options', to='shop.product'),
        ),
    ]
